[tool.poetry]
name = "fw-presidio-image-redactor"
version = "0.1.3"
description = "{{description}}"
authors = ["Flywheel <support@flywheel.io>"]
readme = "README.md"
license = "MIT"
keywords = [
    "Flywheel",
    "Gears"
]
repository = "https://gitlab.com/flywheel-io/scientific-solutions/gears/presidio-image-redactor"
classifiers = [
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
flywheel-sdk = "16.16.7"
presidio-anonymizer = "^2.2.32"
opencv-python = "^4.7.0.68"
python-gdcm = "^3.0.21"
pydicom = "^2.3.1"
presidio-analyzer = "^2.2.32"
flywheel-gear-toolkit = "^0.6.11"
azure-core = "^1.29.5"
azure-ai-ml = "^1.11.1"
azure-ai-formrecognizer = "^3.3.1"
huggingface-hub = "^0.19.4"
transformers = "^4.35.2"
torch = "^2.1.1"
spacy-huggingface-pipelines = "^0.0.4"
easyocr = "^1.7.1"
ruamel-yaml = "^0.18.6"
presidio-image-redactor = "^0.0.53"
spacy = "3.8.3"
fw-file = "^3.4.0"
fw-client = "^0.8.5"
numpy = "1.26.4"
pymongo = "^4.9.1"
pandas = "^2.2.3"
scikit-learn = "^1.5.2"
pytest-mock = "^3.14.0"
botocore = "^1.35.98"
ssm-parameter-store = "^19.11.0"
urllib3 = ">=1.25.4,<1.27"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
pre-commit = "^2.19.0"
poetry-plugin-export = "^1.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.core.masonry.api"
